package kasir_umkm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import popupuser.popupuser10;
import popupuser.popupuser11;

public class Form_user extends javax.swing.JFrame {

    database db = new database();
    public String idUser = "";
    public String username = "";
    public String password = "";
    public String posisi = "";

    // Metode untuk menetapkan data Form_user ke komponen
    public void setProfil(String idUser, String username, String password, String posisi) {
        this.idUser = idUser;
        this.username = username;
        this.password = password;
        this.posisi = posisi;

        // Set nilai ke JTextField
        jiduser.setText(idUser);
        jusername.setText(username);
        jPassword.setText(password);
        jposisi.setText(posisi);

        // Mengatur agar JTextField tidak dapat diedit
        jiduser.setEditable(false);
        jusername.setEditable(false);
        jPassword.setEditable(false);
        jposisi.setEditable(false);
    }

    private void loadProfil(String posisi) {
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_kasir_umkm1", "root", "");
            String query = "SELECT id_user, username, password, posisi FROM users WHERE posisi = ?";
            stmt = conn.prepareStatement(query);
            stmt.setString(1, posisi);

            rs = stmt.executeQuery();

            if (rs.next()) {
                setProfil(
                        rs.getString("id_user"),
                        rs.getString("username"),
                        rs.getString("password"),
                        rs.getString("posisi")
                );
            } else {
                popupuser10 pwSalah = new popupuser10();
                pwSalah.setAlwaysOnTop(true);  // Agar popup berada di depan
                pwSalah.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_user.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat profil: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Form_user.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Konstruktor
    public Form_user() {
        initComponents();
        db.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jiduser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jposisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpengguna = new javax.swing.JLabel();
        jdashboard3 = new javax.swing.JButton();
        jproduk = new javax.swing.JButton();
        jtransaksi = new javax.swing.JButton();
        jlaporan1 = new javax.swing.JButton();
        juser = new javax.swing.JButton();
        jkeluar = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jlihatpassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/seblak.png")).getImage());
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 120, 40));

        jiduser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jiduser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jiduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jiduserActionPerformed(evt);
            }
        });
        getContentPane().add(jiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 120, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 120, 40));

        jusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 250, 40));

        jposisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jposisi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jposisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jposisiActionPerformed(evt);
            }
        });
        getContentPane().add(jposisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 250, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("POSISI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 120, 40));

        jpengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popup/profile.png"))); // NOI18N
        jpengguna.setText("    ");
        jpengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpenggunaMouseClicked(evt);
            }
        });
        getContentPane().add(jpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jdashboard3.setBackground(new java.awt.Color(204, 204, 204));
        jdashboard3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jdashboard3.setText("DASHBOARD");
        jdashboard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdashboard3ActionPerformed(evt);
            }
        });
        getContentPane().add(jdashboard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 60));

        jproduk.setBackground(new java.awt.Color(204, 204, 204));
        jproduk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jproduk.setText("PRODUK");
        jproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprodukActionPerformed(evt);
            }
        });
        getContentPane().add(jproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 200, 60));

        jtransaksi.setBackground(new java.awt.Color(204, 204, 204));
        jtransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtransaksi.setText("TRANSAKSI");
        jtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(jtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 180, 60));

        jlaporan1.setBackground(new java.awt.Color(204, 204, 204));
        jlaporan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlaporan1.setText("LAPORAN");
        jlaporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporan1ActionPerformed(evt);
            }
        });
        getContentPane().add(jlaporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 190, 60));

        juser.setBackground(new java.awt.Color(204, 204, 204));
        juser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        juser.setText("USER");
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        getContentPane().add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 170, 60));

        jkeluar.setBackground(new java.awt.Color(255, 0, 0));
        jkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jkeluar.setText("KELUAR");
        jkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 150, 60));

        jPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 250, 40));

        jlihatpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlihatpassword.setText("Show Password");
        jlihatpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlihatpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlihatpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jlihatpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 460, 250, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/profile1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1282, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jiduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jiduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jiduserActionPerformed

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernameActionPerformed

    private void jposisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jposisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jposisiActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Ambil posisi pengguna yang login, misalnya dari sesi atau database
        String posisiPengguna = Masuk.currentPosisi; // Pastikan variabel ini berisi posisi yang benar (misal 'Kasir' atau 'Owner')
        if (posisiPengguna != null) {
            loadProfil(posisiPengguna); // Panggil loadProfil dengan posisi yang benar
        } else {
            popupuser11 pwSalah = new popupuser11();
            pwSalah.setAlwaysOnTop(true);  // Agar popup berada di depan
            pwSalah.setVisible(true);
        }
    }//GEN-LAST:event_formComponentShown

    private void jpenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpenggunaMouseClicked
        new Form_user().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jpenggunaMouseClicked

    private void jkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkeluarActionPerformed
        new Masuk().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jkeluarActionPerformed

    private void jdashboard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdashboard3ActionPerformed
        new Dashboard_Owner().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jdashboard3ActionPerformed

    private void jprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprodukActionPerformed
        new Data_produk().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jprodukActionPerformed

    private void jtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransaksiActionPerformed
        new Transaksi().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jtransaksiActionPerformed

    private void jlaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporan1ActionPerformed
        new menu_laporan().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jlaporan1ActionPerformed

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        new Data_user().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_juserActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jlihatpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlihatpasswordActionPerformed
        if (jlihatpassword.isSelected()) {
            jPassword.setEchoChar((char) 0);
        } else {
            jPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jlihatpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jdashboard3;
    private javax.swing.JTextField jiduser;
    private javax.swing.JButton jkeluar;
    public static javax.swing.JButton jlaporan1;
    private javax.swing.JCheckBox jlihatpassword;
    private javax.swing.JLabel jpengguna;
    private javax.swing.JTextField jposisi;
    private javax.swing.JButton jproduk;
    private javax.swing.JButton jtransaksi;
    public static javax.swing.JButton juser;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables

}
