package kasir_umkm;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import popuplaporan.popuplaba;
import popuplaporan.popuplaba1;
import popuplaporan.popuplaba2;
import popuplaporan.popuplaba3;

public class laporan_laba extends javax.swing.JFrame {

    database db = new database();

    public laporan_laba() {
        initComponents();
        db.koneksi(); // Panggil metode koneksi saat inisialisasi
    }

    private void hitungLaporan() {
        try {
            int bulan = time.getMonth() + 1;
            int tahun = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
            String bulanFormatted = (bulan < 10 ? "0" : "") + bulan;
            String periode = tahun + "-" + bulanFormatted;

            // Query Pemasukan
            String queryPemasukan = "SELECT SUM(grand_total) AS total_pemasukan FROM penjualan WHERE DATE_FORMAT(tanggal_jual, '%Y-%m') = '" + periode + "'";
            ResultSet rsPemasukan = db.ambildata(queryPemasukan);
            int totalPemasukan = 0;
            if (rsPemasukan != null && rsPemasukan.next()) {
                totalPemasukan = rsPemasukan.getInt("total_pemasukan");
            } else {
                popuplaba laba = new popuplaba();
                laba.setAlwaysOnTop(true);  // Agar popup berada di depan
                laba.setVisible(true);
            }

            // Query Pengeluaran
            String queryPengeluaran = "SELECT SUM(total_harga) AS total_pengeluaran FROM pembelian WHERE DATE_FORMAT(tanggal_beli, '%Y-%m') = '" + periode + "'";
            ResultSet rsPengeluaran = db.ambildata(queryPengeluaran);
            int totalPengeluaran = 0;
            if (rsPengeluaran != null && rsPengeluaran.next()) {
                totalPengeluaran = rsPengeluaran.getInt("total_pengeluaran");
            } else {
                popuplaba1 laba = new popuplaba1();
                laba.setAlwaysOnTop(true);  // Agar popup berada di depan
                laba.setVisible(true);
            }

            // Tampilkan hasil
            pemasukan.setText(String.valueOf(totalPemasukan));
            pengeluaran.setText(String.valueOf(totalPengeluaran));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghitung laporan: " + e.getMessage());
            e.printStackTrace(); // Debugging
        }
    }

    private void hitungLabaBersih() {
        try {
            // Validasi input untuk memastikan kolom tidak kosong
            if (pemasukan.getText().isEmpty() || pengeluaran.getText().isEmpty() || biaya_operasional.getText().isEmpty()) {
                popuplaba2 laba = new popuplaba2();
                laba.setAlwaysOnTop(true);  // Agar popup berada di depan
                laba.setVisible(true);
                return;
            }

            // Parsing nilai dari JTextField sebagai int
            int totalPemasukan = Integer.parseInt(pemasukan.getText());
            int totalPengeluaran = Integer.parseInt(pengeluaran.getText());
            int biayaOperasional = Integer.parseInt(biaya_operasional.getText());

            // Hitung laba bersih
            int labaBersih = totalPemasukan - totalPengeluaran - biayaOperasional;

            // Tampilkan hasil ke JTextField
            laba_bersih.setText(String.valueOf(labaBersih));
        } catch (NumberFormatException e) {
            // Jika ada input yang tidak valid
            popuplaba3 laba = new popuplaba3();
            laba.setAlwaysOnTop(true);  // Agar popup berada di depan
            laba.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new javax.swing.JButton();
        jdashboard = new javax.swing.JButton();
        jproduk = new javax.swing.JButton();
        jlaporan = new javax.swing.JButton();
        juser = new javax.swing.JButton();
        jtransaksi1 = new javax.swing.JButton();
        jkeluar = new javax.swing.JButton();
        time = new com.toedter.calendar.JMonthChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        laba_bersih = new javax.swing.JTextField();
        biaya_operasional = new javax.swing.JTextField();
        pengeluaran = new javax.swing.JTextField();
        pemasukan = new javax.swing.JTextField();
        laporan_laba1 = new com.raven.main.Laporan_laba();
        jpengguna = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/seblak.png")).getImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setBackground(new java.awt.Color(153, 153, 153));
        view.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view.setText("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 120, 50));

        jdashboard.setBackground(new java.awt.Color(204, 204, 204));
        jdashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jdashboard.setText("DASHBOARD");
        jdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdashboardActionPerformed(evt);
            }
        });
        getContentPane().add(jdashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 180, 60));

        jproduk.setBackground(new java.awt.Color(204, 204, 204));
        jproduk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jproduk.setText("PRODUK");
        jproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprodukActionPerformed(evt);
            }
        });
        getContentPane().add(jproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 660, 180, 60));

        jlaporan.setBackground(new java.awt.Color(204, 204, 204));
        jlaporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlaporan.setText("LAPORAN");
        jlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, 170, 60));

        juser.setBackground(new java.awt.Color(204, 204, 204));
        juser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        juser.setText("USER");
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        getContentPane().add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 180, 60));

        jtransaksi1.setBackground(new java.awt.Color(204, 204, 204));
        jtransaksi1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtransaksi1.setText("TRANSAKSI");
        jtransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransaksi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 170, 60));

        jkeluar.setBackground(new java.awt.Color(255, 0, 0));
        jkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jkeluar.setText("KELUAR");
        jkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 140, 50));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pemasukan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Laba Bersih");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 520, 100, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Biaya Operasional");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pengeluaran");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 100, 40));

        laba_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laba_bersihActionPerformed(evt);
            }
        });
        getContentPane().add(laba_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 140, 40));

        biaya_operasional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biaya_operasionalActionPerformed(evt);
            }
        });
        getContentPane().add(biaya_operasional, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 140, 40));
        getContentPane().add(pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 40));
        getContentPane().add(pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 140, 40));
        getContentPane().add(laporan_laba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 650, 460));

        jpengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popup/profile.png"))); // NOI18N
        jpengguna.setText("    ");
        jpengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpenggunaMouseClicked(evt);
            }
        });
        getContentPane().add(jpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Laporan Laba Awal.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1280, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdashboardActionPerformed
        new Dashboard_Owner().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jdashboardActionPerformed

    private void jprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprodukActionPerformed
        new Data_produk().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jprodukActionPerformed

    private void jlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporanActionPerformed
        new menu_laporan().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jlaporanActionPerformed

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        new Data_user().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_juserActionPerformed

    private void jtransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransaksi1ActionPerformed
         new Transaksi().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jtransaksi1ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        hitungLaporan();
    }//GEN-LAST:event_viewActionPerformed

    private void laba_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laba_bersihActionPerformed

    }//GEN-LAST:event_laba_bersihActionPerformed

    private void biaya_operasionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biaya_operasionalActionPerformed
        // TODO add your handling code here:
        hitungLabaBersih();
    }//GEN-LAST:event_biaya_operasionalActionPerformed

    private void jkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkeluarActionPerformed
        new Masuk().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jkeluarActionPerformed

    private void jpenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpenggunaMouseClicked
        new Form_user().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jpenggunaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan_laba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan_laba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan_laba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan_laba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan_laba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaya_operasional;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jdashboard;
    private javax.swing.JButton jkeluar;
    private javax.swing.JButton jlaporan;
    private javax.swing.JLabel jpengguna;
    private javax.swing.JButton jproduk;
    private javax.swing.JButton jtransaksi1;
    private javax.swing.JButton juser;
    private javax.swing.JTextField laba_bersih;
    private com.raven.main.Laporan_laba laporan_laba1;
    private javax.swing.JTextField pemasukan;
    private javax.swing.JTextField pengeluaran;
    private com.toedter.calendar.JMonthChooser time;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
