/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.main;

import com.raven.chart.ModelChart;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.border.LineBorder;

/**
 *
 * @author Tijani Robith
 */
public class Laporan_laba extends javax.swing.JPanel {

    public Laporan_laba() {
        initComponents();

        // Set panel background and chart styling
        setBackground(new Color(245, 245, 245));
        chart.setBorder(new LineBorder(new Color(180, 180, 180), 2));

        // Customize chart legends with modern colors
        chart.addLegend("Penjualan", new Color(33, 150, 243));
        chart.addLegend("Pembelian", new Color(244, 67, 54));

        // Set font for the chart
        chart.setFont(new Font("SansSerif", Font.BOLD, 14));

        // Fetch and display chart data
        List<ModelChart> chartData = getChartData();
        for (ModelChart data : chartData) {
            chart.addData(data);
        }
    }

    private List<ModelChart> getChartData() {
        List<ModelChart> dataList = new ArrayList<>();
        String url = "jdbc:mysql://localhost:3306/db_kasir_umkm1";
        String user = "root";
        String password = "";

        String query = "SELECT m.month AS month, "
                + "COALESCE(SUM(penjualan.grand_total), 0) AS total_penjualan, "
                + "COALESCE(SUM(pembelian.total_harga), 0) AS total_pembelian "
                + "FROM ("
                + "  SELECT 1 AS month UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL "
                + "  SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 "
                + ") m "
                + "LEFT JOIN penjualan ON MONTH(penjualan.tanggal_jual) = m.month "
                + "LEFT JOIN pembelian ON MONTH(pembelian.tanggal_beli) = m.month "
                + "GROUP BY m.month "
                + "ORDER BY m.month";

        String[] bulanIndonesia = {"Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Des"};

        try (Connection conn = DriverManager.getConnection(url, user, password); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                int monthIndex = rs.getInt("month") - 1; // Convert 1-based month to 0-based index
                String label = bulanIndonesia[monthIndex];
                double totalPenjualan = rs.getDouble("total_penjualan");
                double totalPembelian = rs.getDouble("total_pembelian");
                
                chart.clear();
                dataList.add(new ModelChart(label, new double[]{totalPenjualan, totalPembelian}));
                chart.start();
            }
        } catch (Exception e) {
            System.err.println("Database connection or query error:");
            e.printStackTrace();
        }

        return dataList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new com.raven.chart.Chart();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafik_Bulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafik_Bulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafik_Bulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafik_Bulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Dashboard Laporan Laba");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setSize(600, 450);
            frame.add(new Laporan_laba());
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    // End of variables declaration//GEN-END:variables
}
